// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6lAalfgsUpgspCGTAYPlH2Q3pC8VhBEw',
    appId: '1:284791684819:web:6d4bfaaf76323c83719e26',
    messagingSenderId: '284791684819',
    projectId: 'whats-app-clone-4fe8a',
    authDomain: 'whats-app-clone-4fe8a.firebaseapp.com',
    storageBucket: 'whats-app-clone-4fe8a.appspot.com',
    measurementId: 'G-B04MVE99MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcREdwziOrVo8T7KuDY44B08tC3dT8C9Y',
    appId: '1:284791684819:android:6b98c82b53cb3aaf719e26',
    messagingSenderId: '284791684819',
    projectId: 'whats-app-clone-4fe8a',
    storageBucket: 'whats-app-clone-4fe8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFybXFUNZJDChlEnMdK6GXVBXeidNSimU',
    appId: '1:284791684819:ios:dbcfcc1822ed136b719e26',
    messagingSenderId: '284791684819',
    projectId: 'whats-app-clone-4fe8a',
    storageBucket: 'whats-app-clone-4fe8a.appspot.com',
    androidClientId: '284791684819-7u80h1end78abvjjehd2vk8gto5rp233.apps.googleusercontent.com',
    iosClientId: '284791684819-km23ttvhaeic0ueam3i8igi47u2pq0vb.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsAppClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFybXFUNZJDChlEnMdK6GXVBXeidNSimU',
    appId: '1:284791684819:ios:865ea1ab4ede039b719e26',
    messagingSenderId: '284791684819',
    projectId: 'whats-app-clone-4fe8a',
    storageBucket: 'whats-app-clone-4fe8a.appspot.com',
    androidClientId: '284791684819-7u80h1end78abvjjehd2vk8gto5rp233.apps.googleusercontent.com',
    iosClientId: '284791684819-ql8dck4smaijrs3tphv2tqp4te1enj9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsAppClone.RunnerTests',
  );
}
